import Head from "next/head";
import commerce from "../utils/data";
import { Product } from "../components/products/product";
import { Slider } from "../components/Slider/slider";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [prodClick, setProdClick] = useState();
  const randomProd =
    prodClick || commerce[Math.floor(Math.random() * commerce.length)];

  return (
    <div className={styles.container}>
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Product prod={randomProd} />
      <Slider
        all={commerce.filter((el) => el != randomProd)}
        setProdClick={setProdClick}
      />
    </div>
  );
}
